### ISSUE TITLE
Uncaught TypeError: target.getModel is not a function

### ISSUE THREAD

**Issue by thatsprettyfaroutman** [aki77/atom-gist#5]
[Enter steps to reproduce below:]
1. Tried to list gists

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [gist](https://github.com/aki77/atom-gist) package, v0.2.6
### Stack Trace

Uncaught TypeError: target.getModel is not a function

```
At /Users/vil/.atom/packages/gist/lib/main.coffee:40

TypeError: target.getModel is not a function
  at atom-text-editor.subscriptions.add.atom.commands.add.gist:list (/Users/vil/.atom/packages/gist/lib/main.coffee:40:47)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:528:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:351:22)
  at HTMLDocument.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:20)

```
### Commands

```
     -0:46.6.0 core:backspace (input.hidden-input)
     -0:45 core:undo (input.hidden-input)
     -0:41 command-palette:toggle (input.hidden-input)
     -0:38 core:confirm (input.hidden-input)
     -0:38 gist:list (input.hidden-input)
     -0:28.1.0 command-palette:toggle (input.hidden-input)
     -0:25.9.0 core:move-down (input.hidden-input)
     -0:23.9.0 core:confirm (input.hidden-input)
     -0:23.9.0 gist:create-public (input.hidden-input)
     -0:07.6.0 command-palette:toggle (input.hidden-input)
  3x -0:05.0 core:move-down (input.hidden-input)
  3x -0:03.0 core:move-up (input.hidden-input)
     -0:02.3.0 core:confirm (input.hidden-input)
     -0:02.3.0 gist:list (input.hidden-input)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "chester-atom-syntax"
    ],
    "disabledPackages": [
      "git-plus",
      "auto-indent",
      "SFTP-deployment",
      "jsdoc",
      "language-cshtml",
      "merge-conflicts",
      "project-manager",
      "Remote-FTP",
      "atom-color-highlight"
    ],
    "packagesWithKeymapsDisabled": [
      "tidy-tabs"
    ]
  },
  "gist": {
    "token": "cf97a5660ab7270ddbc997ea93eebd5f54eb4a10"
  }
}
```
### Installed Packages

``` coffee
# User
aligner, v0.17.1
atom-pair, v2.0.10
atom-ternjs, v0.8.4
change-case, v0.6.0
chester-atom-syntax, v0.1.1
emmet, v2.3.13
file-icons, v1.6.11
gist, v0.2.6
minimap, v4.15.1
php-cs-fixer, v2.5.1
php-twig, v4.0.0
remote-sync, v3.1.2
symbols-tree-view, v0.10.1
sync-settings, v0.6.0
tidy-tabs, v0.3.0

# Dev
No dev packages
```

**Comment by aki77** [comment]
Please try the latest version.

https://github.com/aki77/atom-expand-region/issues/1#issuecomment-132111333

**Comment by thatsprettyfaroutman** [comment]
Yup, now it works, thanks!
